# PDF parsing → chunking → embedding → storage → retrieval
# keep separated from agent.py and tools.py, follow the single responsibility principle

import pdfplumber
import chromadb
from chromadb.utils import embedding_functions
import os
from dotenv import load_dotenv

load_dotenv()

# ─────────────────────────────────────────
# Embedding function
openai_ef = embedding_functions.OpenAIEmbeddingFunction(
    api_key=os.environ.get("OPENAI_API_KEY"),
    model_name="text-embedding-3-small"
)

def extract_text_from_pdf(pdf_bytes: bytes) -> str:
    """
    Extract text from PDF, using dual engine strategy:
    
    Primary engine: pymupdf (fitz)
    Advantage: can handle complex layouts, text boxes, special fonts
    Suitable for most resumes generated by Word/design software
    
    Backup engine: pdfplumber  
    Advantage: better preserves paragraph structure for standard PDF
    Suitable for simple layouts
    
    Strategy:先用 pymupdf 提取，如果词数明显更多就用它，
    Otherwise fallback to pdfplumber results, choose the one with more words
    """
    import io
    import fitz  # pymupdf's import name is fitz

    # ── 方案一：pymupdf ──────────────────────────────
    fitz_text_parts = []
    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    for page in doc:
        # "text" mode extracts plain text
        # "dict" mode can get a more detailed structure, but we don't need it for now
        page_text = page.get_text("text")
        if page_text.strip():
            fitz_text_parts.append(page_text.strip())
    doc.close()
    fitz_text = "\n\n".join(fitz_text_parts)

    # ── Strategy 2: pdfplumber ───────────────────────────
    import pdfplumber
    plumber_text_parts = []
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                plumber_text_parts.append(page_text.strip())
    plumber_text = "\n\n".join(plumber_text_parts)

    # ── Choose the one with more words ─────────────────────────────
    # This is a simple but effective heuristic rule:
    # The scheme that extracts more words usually means it handles the PDF format better
    fitz_words = len(fitz_text.split())
    plumber_words = len(plumber_text.split())
    
    chosen_text = fitz_text if fitz_words >= plumber_words else plumber_text
    chosen_engine = "pymupdf" if fitz_words >= plumber_words else "pdfplumber"
    
    print(f"PDF extraction: pymupdf={fitz_words} words, "
          f"pdfplumber={plumber_words} words, "
          f"using {chosen_engine}")

    if len(chosen_text.split()) < 100:
        print(f"Warning: only {len(chosen_text.split())} words extracted. "
              f"PDF may contain scanned images or unsupported formatting.")

    return chosen_text


# ─────────────────────────────────────────
# Text chunking
# This is one of the most important design decisions in RAG
# ─────────────────────────────────────────
def chunk_resume(text: str) -> list[str]:
    import re
    
    # Step 1: Clean all invisible characters
    text = text.replace('\u200b', '').replace('\xa0', ' ')
    text = re.sub(r'[ \t]+', ' ', text)
    
    # Step 2: Add double newline before bullet points
    # Do this first, turn each experience into a separate paragraph
    text = re.sub(r'\n●', '\n\n●', text)
    
    # Step 3: Add double newline after section headers
    # Note: here we match the newline after the header, not the previous content
    # Reason: the content before the header is not fixed, but the header is always followed by \n
    # Use \b to ensure only matching complete words, avoid false matches
    section_pattern = r'(EXPERIENCE|EDUCATION|SKILLS|PROJECTS|AWARDS|CERTIFICATIONS|OTHER EXPERIENCE|PROGRAMMING)[^\n]*\n'
    text = re.sub(section_pattern, lambda m: m.group() + '\n', text)
    
    # Step 4: Split by double newline
    paragraphs = [p.strip() for p in text.split('\n\n') if p.strip()]
    
    # Step 5: Merge logic - only merge very short fragments (e.g. isolated header lines)
    # Reduce the threshold from 15 words to 5 words, avoid merging complete bullet points
    chunks = []
    current = ""
    
    for para in paragraphs:
        word_count = len(para.split())
        if word_count < 8:
            # Only merge very short fragments (e.g. isolated "SKILLS" line)
            current = (current + "\n" + para).strip()
        elif len(current.split()) + word_count > 80:
            if current:
                chunks.append(current)
            current = para
        else:
            current = (current + "\n\n" + para).strip()
    
    if current:
        chunks.append(current)
    
    return [c for c in chunks if len(c.split()) > 10]


# ─────────────────────────────────────────
# ChromaDB Session management
# 
# Important design decision: use in-memory client, not persistent
# Reason: resume is sensitive personal data
#       session ends and data is cleared, protect user privacy
#      Each time the upload is re-indexed to ensure fresh data
#
# If it's company intelligence cache (Feature 2), will use persistent client
# This comparison itself is a good interview question
# ─────────────────────────────────────────
class ResumeRAG:
    """
    Wrap the RAG lifecycle of the resume in a class
    Each user session corresponds to a ResumeRAG instance
    When the instance is destroyed, the in-memory data of ChromaDB is automatically cleared
    """
    
    def __init__(self, session_id: str = ""):
        # in-memory client: process memory, not written to disk
        import uuid
        self.collection_name = session_id or str(uuid.uuid4())  
        self.client = chromadb.Client()
        self.collection = self.client.create_collection(
        name=self.collection_name,  # 用 session_id 代替硬编码的 "resume"
        embedding_function=openai_ef,
        metadata={"hnsw:space": "cosine"}
    )
        self.has_resume = False
    
    def index_resume(self, pdf_bytes: bytes) -> int:
        """
        Parse PDF, chunk, and store in ChromaDB
        Return the number of chunks successfully stored
        """
        text = extract_text_from_pdf(pdf_bytes)
        chunks = chunk_resume(text)

        if not chunks:
            raise ValueError("Could not extract meaningful text from PDF. "
                             "Please ensure the PDF contains selectable text (not a scanned image).")
        print(f"Indexed {len(chunks)} chunks from resume")
        
        # ChromaDB requires each document to have a unique ID
        ids = [f"chunk_{i}" for i in range(len(chunks))]
        
        # add() will automatically call the embedding_function to convert the text into a vector
        # and store it in the in-memory vector database
        self.collection.add(
            documents=chunks,
            ids=ids
        )
        
        self.has_resume = True
        return len(chunks)
    
    def retrieve(self, query: str, n_results: int = 3) -> str:
        """
        Use JD text as query, retrieve the most relevant chunks in the resume
        
        Reason: Too few (1) may miss important information
                Too many (5+) will introduce noise, prompt too long
                Reasonable number of results is 3
        """
        if not self.has_resume:
            return ""
        
        results = self.collection.query(
            query_texts=[query],
            n_results=min(n_results, self.collection.count())
        )
        
        # results["documents"] is a list of lists
        # the first element is the result of the first query (we only have one query)
        retrieved_chunks = results["documents"][0]
        
        # use delimiter to connect, make it easier for LLM to distinguish different resume chunks
        return "\n---\n".join(retrieved_chunks)